#! /bin/sh

set -e

. /usr/share/debconf/confmodule
case $1 in
    configure)
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 0
    ;;
esac

#DEBHELPER#
